// packages/engine/scripts/npm-wrapper.ts
//
// Dogfood (spec self-consumes this repo — see spec-engine/):
// @spec DIST-003
//
// Source of the published bin entry (dist/cli.js), exported as a string so
// the guard-before-import ordering is unit-testable without running a build
// (test/npm-package.test.ts).
//
// Why a wrapper exists at all: the bundle (dist/impl.js) statically imports
// bun:sqlite, which a non-Bun ESM loader fails to RESOLVE — before any inline
// guard could execute. The wrapper checks the runtime first and only then
// dynamically imports the bundle, so a Node user gets an actionable message
// instead of ERR_UNKNOWN_BUILTIN_MODULE. `engines.bun` alone cannot do this
// (advisory unless the consumer sets engine-strict), and postinstall checks
// are blocked by Bun's default trustedDependencies policy.

export const wrapperSource = `#!/usr/bin/env bun
// Generated by packages/engine/scripts/build-npm.ts — do not edit.
if (typeof Bun === "undefined") {
  console.error(
    "spec requires the Bun runtime (the index engine uses bun:sqlite).\\n" +
      "Install Bun >= 1.3 from https://bun.sh and re-run, e.g.:\\n" +
      "  bunx @spec-engine/spec-engine --help",
  );
  process.exit(1);
}
await import("./impl.js");
`;
